name: Upload website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete 
                  --exclude ".git/*" --exclude ".github/*"
                  --exclude ".gitignore" --exclude "README.md"
                  $SOURCE_DIR s3://${{ secrets.darren-cloud-resume-challenge}}/Resume
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          SOURCE_DIR: 'Resume HTML'